# 개발 환경 hot-reload 환경
# backend package.json devDependencies "ts-node-dev": "^2.0.0" 추가
# docker compose -f docker-compose.yml -f docker-compose.dev.yml down
# docker compose -f docker-compose.yml -f docker-compose.dev.yml up --build

# prisma 듀얼 DB 환경
# docker compose exec backend npx prisma db push --schema prisma/mongodb/schema.prisma
# docker compose exec backend npx prisma db push --schema prisma/postgres/schema.prisma
# docker compose exec backend npx prisma generate --schema prisma/postgres/schema.prisma
# docker compose exec backend npx prisma generate --schema prisma/mongodb/schema.prisma

#mongo db 환경 
# docker run --rm alpine sh -c "apk add --no-cache openssl && openssl rand -base64 756" > mongo-keyfile
# docker run --rm -v ${PWD}:/data alpine chmod 400 /data/mongo-keyfile
#docker로 mongo db 로 접근하여 아래 명령 수행
#rs.initiate({
#   _id: "rs0",
#   members: [
#     {
#       _id: 0,
#       host: "mongodb:27017"
#     }
#   ]
# })
# rs.status()

#MongoDB Conversation Index 재생성 - group채팅을 위함
# db.Conversation.dropIndex("Conversation_directKey_key")

# db.Conversation.createIndex(
#   { directKey: 1 },
#   {
#     unique: true,
#     partialFilterExpression: {
#       directKey: { $type: "string" }
#     },
#     name: "Conversation_directKey_key"
#   }
# )


services:


  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - tap-lang-network

  # 1. PostgreSQL 데이터베이스
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tap-lang-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tap_lang_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  mongodb:
      image: mongo:7
      container_name: mongodb
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
        MONGO_INITDB_DATABASE: ${DB_NAME}
      ports:
        - "27017:27017"
      volumes:
        - ./mongo-data:/data/db
        - ./mongo-keyfile:/etc/mongo-keyfile
      networks:
        - tap-lang-network  

      command: >
        sh -c "chmod 400 /etc/mongo-keyfile && exec mongod --replSet rs0 --keyFile /etc/mongo-keyfile --bind_ip_all"
      

  # 2. Redis (Socket.IO 어댑터 및 캐싱용)
  redis:
    image: redis:7-alpine
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"
    networks:
      - tap-lang-network
    command: redis-server --notify-keyspace-events Ex 

  # 3. Node.js + Socket.IO 백엔드
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node_js
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"

    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${APP_PORT}
      POSTGRES_DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}?schema=public"
      MONGODB_DATABASE_URL: "mongodb://${DB_USER}:${DB_PASSWORD}@mongodb:27017/${DB_NAME}?authSource=admin&replicaSet=rs0"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      UPLOAD_DIR: ${UPLOAD_DIR}
      ADMIN_PROVIDER_ID: ${ADMIN_PROVIDER_ID}
    depends_on:
      - postgres
      - redis
    volumes:
      - ${UPLOAD_HOST_DIR}:${UPLOAD_DIR}  
    command: sh -c "npm start"

    networks:
      - tap-lang-network

    

  # 4. Vue.js + TypeScript 프론트엔드 (개발용)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vite
    restart: always
    ports:
      - ${NGINX_PORT} #nginx 포트
    environment:
      - VITE_API_URL= ${VITE_API_URL}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - tap-lang-network




volumes:
  pgdata:

networks:
  tap-lang-network:
    driver: bridge