# prisma 스키마 db 생성 
# - docker compose exec backend  npx prisma migrate dev
  services:
    backend:
      build:
        dockerfile: Dockerfile.dev
      environment:
        NODE_ENV: development

      depends_on:
        postgres:
          condition: service_healthy
        mongo:
          condition: service_started  

      volumes:
        - ./backend:/usr/src/app
        - /usr/src/app/node_modules 
      command: sh -c "npm run dev"

    frontend:
      build:
        dockerfile: Dockerfile.dev
      ports:
        - "5174:5174"
      volumes:
        - ./frontend:/usr/src/app
        - /usr/src/app/node_modules
      environment:
        - VITE_API_URL=http://localhost:3000