FROM node:22-alpine

RUN apk add --no-cache openssl

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

COPY prisma ./prisma
COPY src ./src

EXPOSE 3000

CMD ["npm", "run", "dev"]