import { defineStore } from 'pinia'
import { computed, ref } from 'vue'
import type { Country } from '@/types'

export const useCountryStore = defineStore('country', () => {
 const countries = ref<Country[]>([
  // 동아시아
  { code: 'KR', name: '대한민국', flag: 'kr' },
  { code: 'US', name: '미국', flag: 'us' },
  { code: 'JP', name: '일본', flag: 'jp' },
  { code: 'CN', name: '중국', flag: 'cn' },
  { code: 'TW', name: '대만', flag: 'tw' },
  { code: 'HK', name: '홍콩', flag: 'hk' },
  { code: 'MO', name: '마카오', flag: 'mo' },
  { code: 'MN', name: '몽골', flag: 'mn' },

  // 유럽
  { code: 'GB', name: '영국', flag: 'gb' },
  { code: 'FR', name: '프랑스', flag: 'fr' },
  { code: 'DE', name: '독일', flag: 'de' },
  { code: 'IT', name: '이탈리아', flag: 'it' },
  { code: 'ES', name: '스페인', flag: 'es' },
  { code: 'PT', name: '포르투갈', flag: 'pt' },
  { code: 'NL', name: '네덜란드', flag: 'nl' },
  { code: 'BE', name: '벨기에', flag: 'be' },
  { code: 'CH', name: '스위스', flag: 'ch' },
  { code: 'AT', name: '오스트리아', flag: 'at' },
  { code: 'SE', name: '스웨덴', flag: 'se' },
  { code: 'NO', name: '노르웨이', flag: 'no' },
  { code: 'DK', name: '덴마크', flag: 'dk' },
  { code: 'FI', name: '핀란드', flag: 'fi' },
  { code: 'IS', name: '아이슬란드', flag: 'is' },
  { code: 'PL', name: '폴란드', flag: 'pl' },
  { code: 'CZ', name: '체코', flag: 'cz' },
  { code: 'SK', name: '슬로바키아', flag: 'sk' },
  { code: 'HU', name: '헝가리', flag: 'hu' },
  { code: 'RO', name: '루마니아', flag: 'ro' },
  { code: 'BG', name: '불가리아', flag: 'bg' },
  { code: 'HR', name: '크로아티아', flag: 'hr' },
  { code: 'SI', name: '슬로베니아', flag: 'si' },
  { code: 'RS', name: '세르비아', flag: 'rs' },
  { code: 'BA', name: '보스니아 헤르체고비나', flag: 'ba' },
  { code: 'ME', name: '몬테네그로', flag: 'me' },
  { code: 'MK', name: '북마케도니아', flag: 'mk' },
  { code: 'AL', name: '알바니아', flag: 'al' },
  { code: 'GR', name: '그리스', flag: 'gr' },
  { code: 'IE', name: '아일랜드', flag: 'ie' },
  { code: 'LT', name: '리투아니아', flag: 'lt' },
  { code: 'LV', name: '라트비아', flag: 'lv' },
  { code: 'EE', name: '에스토니아', flag: 'ee' },
  { code: 'LU', name: '룩셈부르크', flag: 'lu' },
  { code: 'MT', name: '몰타', flag: 'mt' },
  { code: 'CY', name: '키프로스', flag: 'cy' },
  { code: 'MC', name: '모나코', flag: 'mc' },
  { code: 'LI', name: '리히텐슈타인', flag: 'li' },
  { code: 'AD', name: '안도라', flag: 'ad' },
  { code: 'SM', name: '산마리노', flag: 'sm' },
  { code: 'VA', name: '바티칸', flag: 'va' },
  { code: 'BY', name: '벨라루스', flag: 'by' },
  { code: 'MD', name: '몰도바', flag: 'md' },
  { code: 'RU', name: '러시아', flag: 'ru' },
  { code: 'UA', name: '우크라이나', flag: 'ua' },

  // 북아메리카/중남미
  { code: 'CA', name: '캐나다', flag: 'ca' },
  { code: 'MX', name: '멕시코', flag: 'mx' },
  { code: 'GT', name: '과테말라', flag: 'gt' },
  { code: 'BZ', name: '벨리즈', flag: 'bz' },
  { code: 'HN', name: '온두라스', flag: 'hn' },
  { code: 'SV', name: '엘살바도르', flag: 'sv' },
  { code: 'NI', name: '니카라과', flag: 'ni' },
  { code: 'CR', name: '코스타리카', flag: 'cr' },
  { code: 'PA', name: '파나마', flag: 'pa' },
  { code: 'CU', name: '쿠바', flag: 'cu' },
  { code: 'DO', name: '도미니카공화국', flag: 'do' },
  { code: 'JM', name: '자메이카', flag: 'jm' },
  { code: 'BS', name: '바하마', flag: 'bs' },
  { code: 'TT', name: '트리니다드 토바고', flag: 'tt' },
  { code: 'PR', name: '푸에르토리코', flag: 'pr' },
  { code: 'BR', name: '브라질', flag: 'br' },
  { code: 'AR', name: '아르헨티나', flag: 'ar' },
  { code: 'CL', name: '칠레', flag: 'cl' },
  { code: 'CO', name: '콜롬비아', flag: 'co' },
  { code: 'PE', name: '페루', flag: 'pe' },
  { code: 'VE', name: '베네수엘라', flag: 've' },
  { code: 'EC', name: '에콰도르', flag: 'ec' },
  { code: 'BO', name: '볼리비아', flag: 'bo' },
  { code: 'PY', name: '파라과이', flag: 'py' },
  { code: 'UY', name: '우루과이', flag: 'uy' },

  // 오세아니아
  { code: 'AU', name: '호주', flag: 'au' },
  { code: 'NZ', name: '뉴질랜드', flag: 'nz' },
  { code: 'FJ', name: '피지', flag: 'fj' },
  { code: 'PG', name: '파푸아뉴기니', flag: 'pg' },
  { code: 'WS', name: '사모아', flag: 'ws' },
  { code: 'TO', name: '통가', flag: 'to' },

  // 남아시아/동남아시아
  { code: 'IN', name: '인도', flag: 'in' },
  { code: 'PK', name: '파키스탄', flag: 'pk' },
  { code: 'BD', name: '방글라데시', flag: 'bd' },
  { code: 'LK', name: '스리랑카', flag: 'lk' },
  { code: 'NP', name: '네팔', flag: 'np' },
  { code: 'BT', name: '부탄', flag: 'bt' },
  { code: 'MV', name: '몰디브', flag: 'mv' },
  { code: 'ID', name: '인도네시아', flag: 'id' },
  { code: 'TH', name: '태국', flag: 'th' },
  { code: 'VN', name: '베트남', flag: 'vn' },
  { code: 'PH', name: '필리핀', flag: 'ph' },
  { code: 'MY', name: '말레이시아', flag: 'my' },
  { code: 'SG', name: '싱가포르', flag: 'sg' },
  { code: 'MM', name: '미얀마', flag: 'mm' },
  { code: 'LA', name: '라오스', flag: 'la' },
  { code: 'KH', name: '캄보디아', flag: 'kh' },
  { code: 'BN', name: '브루나이', flag: 'bn' },
  { code: 'TL', name: '동티모르', flag: 'tl' },

  // 중앙아시아
  { code: 'KZ', name: '카자흐스탄', flag: 'kz' },
  { code: 'UZ', name: '우즈베키스탄', flag: 'uz' },
  { code: 'KG', name: '키르기스스탄', flag: 'kg' },
  { code: 'TJ', name: '타지키스탄', flag: 'tj' },
  { code: 'TM', name: '투르크메니스탄', flag: 'tm' },

  // 중동
  { code: 'TR', name: '튀르키예', flag: 'tr' },
  { code: 'SA', name: '사우디아라비아', flag: 'sa' },
  { code: 'AE', name: '아랍에미리트', flag: 'ae' },
  { code: 'IL', name: '이스라엘', flag: 'il' },
  { code: 'IQ', name: '이라크', flag: 'iq' },
  { code: 'IR', name: '이란', flag: 'ir' },
  { code: 'JO', name: '요르단', flag: 'jo' },
  { code: 'LB', name: '레바논', flag: 'lb' },
  { code: 'SY', name: '시리아', flag: 'sy' },
  { code: 'YE', name: '예멘', flag: 'ye' },
  { code: 'OM', name: '오만', flag: 'om' },
  { code: 'QA', name: '카타르', flag: 'qa' },
  { code: 'KW', name: '쿠웨이트', flag: 'kw' },
  { code: 'BH', name: '바레인', flag: 'bh' },
  { code: 'AF', name: '아프가니스탄', flag: 'af' },
  { code: 'GE', name: '조지아', flag: 'ge' },
  { code: 'AM', name: '아르메니아', flag: 'am' },
  { code: 'AZ', name: '아제르바이잔', flag: 'az' },

  // 아프리카
  { code: 'EG', name: '이집트', flag: 'eg' },
  { code: 'ZA', name: '남아프리카공화국', flag: 'za' },
  { code: 'NG', name: '나이지리아', flag: 'ng' },
  { code: 'KE', name: '케냐', flag: 'ke' },
  { code: 'ET', name: '에티오피아', flag: 'et' },
  { code: 'GH', name: '가나', flag: 'gh' },
  { code: 'TZ', name: '탄자니아', flag: 'tz' },
  { code: 'UG', name: '우간다', flag: 'ug' },
  { code: 'DZ', name: '알제리', flag: 'dz' },
  { code: 'MA', name: '모로코', flag: 'ma' },
  { code: 'TN', name: '튀니지', flag: 'tn' },
  { code: 'LY', name: '리비아', flag: 'ly' },
  { code: 'SD', name: '수단', flag: 'sd' },
  { code: 'CI', name: '코트디부아르', flag: 'ci' },
  { code: 'SN', name: '세네갈', flag: 'sn' },
  { code: 'CM', name: '카메룬', flag: 'cm' },
  { code: 'ZM', name: '잠비아', flag: 'zm' },
  { code: 'ZW', name: '짐바브웨', flag: 'zw' },
  { code: 'MZ', name: '모잠비크', flag: 'mz' },
  { code: 'AO', name: '앙골라', flag: 'ao' },
  { code: 'NA', name: '나미비아', flag: 'na' },
  { code: 'BW', name: '보츠와나', flag: 'bw' },
  { code: 'RW', name: '르완다', flag: 'rw' },
  { code: 'MG', name: '마다가스카르', flag: 'mg' },
  { code: 'MU', name: '모리셔스', flag: 'mu' },

  { code: 'UNKNOWN', name: '기타 지역', flag: 'xx' }
])
 

  const getByCode = computed(() => {
    return (code: string) =>
      countries.value.find(country => country.code === code)
  })

  return {
    countries,
    getByCode
  }
})